# @format

name: main

on:
  # schedule:
  #   - cron: "00 13 * * 6"
  workflow_dispatch:

jobs:
  update:
    name: update-note
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install Dependence
        run: pip install -r requirements.txt
      - name: Run main.py
        run: python main.py --token '${{ secrets.TOKEN }}' --note '${{ secrets.NOTE }}' --webhook '${{ secrets.WEBHOOK }}'

      - name: Update done.txt
        id: update_done
        continue-on-error: true
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m 'update done'
          git push -u origin main
